name: Build and Release

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: adopt
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean plugin-core:shadowJar

    - name: Upload JAR file
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Dream-Template
        path: plugin-core/build/libs/*.jar
